# -*- coding: utf-8 -*-
"""flex_MiniMart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIxzMc-57NDMN8JzeUFRbGAN6-oE52ro
"""

from ultralytics import YOLO

model = YOLO("C:\\Users\\ptplokee\\source\\repos\\MiniMart\\weights\\best.pt")  # load the best model

"""# inference / predict"""
import cv2

# Open the default camera
cam = cv2.VideoCapture(0)

# Get the default frame width and height
frame_width = int(cam.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cam.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Define the codec and create VideoWriter object
#fourcc = cv2.VideoWriter_fourcc(*'mp4v')
#out = cv2.VideoWriter('output.mp4', fourcc, 20.0, (frame_width, frame_height))
results=model.track(source=1, show=True, conf=0.8)

#while True:
#    ret, frame = cam.read()

#    # Write the frame to the output file
#    out.write(frame)

#    # Display the captured frame
#    cv2.imshow('Camera', frame)

#    # Press 'q' to exit the loop
#    if cv2.waitKey(1) == ord('q'):
#        break

## Release the capture and writer objects
#cam.release()
#out.release()
#cv2.destroyAllWindows()